version: "3.9"
services:
  minecraft:
    build: 
      context: ./minecraft
      args: 
        MINECRAFT_VERSION: 1.20.4
    volumes:
      - ./minecraft-data:/minecraft-server/data
    ports:
      - 25566:25565
    environment:
      - eula=false
    stdin_open: true 
    tty: true
    depends_on: 
      - ngrok

  ngrok:
    image: ngrok/ngrok
    environment:
      - NGROK_AUTHTOKEN
    command: 'tcp minecraft:25565'
    ports:
      - 4040:4040


