version: "3.9"
services:
  minecraft:
    build: 
      context: ./minecraft
      args: #1.19.2
        JAR_DOWNLOAD_LINK: https://piston-data.mojang.com/v1/objects/f69c284232d7c7580bd89a5a4931c3581eae1378/server.jar
    volumes:
      - ./minecraft-data:/minecraft-server/data
    ports:
      - 25566:25565
    environment:
      - eula=false
    depends_on: 
      - ngrok
    stdin_open: true 
    tty: true

  ngrok:
    image: ngrok/ngrok
    environment:
      - NGROK_AUTHTOKEN
    command: 'tcp minecraft:25565'
    ports:
      - 4040:4040


